### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by th0s** [Flux159/cassie-odm#9]
CQL Query:  CREATE KEYSPACE IF NOT EXISTS cassietest WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }
Listening on port 1337
-----
CQL Describe Keyspace Query:  SELECT * FROM system_schema.tables WHERE keyspace_name=?
CQL Parameters:  ["ad_service"]
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'info' of undefined
    at /mnt/c/Users//Desktop//node_modules/cassie-odm/lib/cassie.js:170:20
    at /mnt/c/Users//Desktop//node_modules/cassie-odm/lib/query.js:413:43
    at next (/mnt/c/Users/t/Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/utils.js:613:14)
    at EventEmitter.<anonymous> (/mnt/c/Users/t/Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/client.js:690:9)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /mnt/c/Users//Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/client.js:864:19
    at RequestHandler.handleError (/mnt/c/Users//Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/request-handler.js:316:12)
    at readCallback (/mnt/c/Users//Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/request-handler.js:179:19)
    at Connection.invokeCallback (/mnt/c/Users/t/Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/connection.js:584:5)
Emitted 'error' event at:
    at Protocol.onerror (_stream_readable.js:687:12)
    at Protocol.emit (events.js:182:13)
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at Protocol.afterTransform (_stream_transform.js:94:3)
    at Protocol._transform (/mnt/c/Users//Desktop//node_modules/cassie-odm/node_modules/cassandra-driver/lib/streams.js:37:3)    at Protocol.Transform._read (_stream_transform.js:190:10)
    at Protocol.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)

Got this after copying and pasting your Documentation code sample.

**Comment by Flux159** [comment]
Whoops, seems there was an issue w/ logger not being defined at that point - can you update to 0.3.2? It should be fixed in that (just published). Also, this code was written a long time ago before I knew of eslint, Typescript / Flow, so there are definitely improvements that could be made. Thanks for the bug report!

**Comment by Flux159** [comment]
Also, which documentation example did you see that uses SELECT * FROM system_schema.tables? Want to clean up the docs if possible
